accounts/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path

from django.contrib.auth import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("pages.urls")),
    path("posts/", include("posts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
]

pages/urls.py
from django.urls import path
from .views import HomePageView, AboutPageView


urlpatterns =[
    path("", HomePageView.as_view(), name="home"),
    path("about/", AboutPageView.as_view(), name="about"),
]

posts/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostUpdateView,
    PostDeleteView,
    PostDetailView,
    PostCreateView,
)

urlpatterns = [
    path("", PostListView.as_view(), name="list"),
    path("new/", PostCreateView.as_view(), name="new"),
    path("<int:pk>/", PostDetailView.as_view(), name="detail"),
    path("<int:pk>/edit/", PostUpdateView.as_view(), name="edit"),
    path("<int:pk>/delete/", PostDeleteView.as_view(), name="delete"),
]
# Creating template and urlpatterns for:
# PostListView
# PostDeleteView
# PostCreateView

accounts/models.py
from django.db import models

# Create your models here.

pages/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.urls import reverse


class Post(models.Model):
    title = models.CharField(max_length=128)
    subtitle = models.CharField(max_length=128)
    author = models.ForeignKey(
        'auth.User',
        on_delete=models.CASCADE
    )
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
                                 
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("detail", args=[self.id])
    

accounts/views.py
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy


class SignUpView(CreateView):
    template_name = "registration/signup.html"
    form_class = UserCreationForm
    success_url = reverse_lazy("login")


# Create your views here.

pages/views.py
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = "pages/home.html"

class AboutPageView(TemplateView):
    template_name = "pages/about.html" 

posts/views.py
from django.views.generic import (
    CreateView,
    DeleteView,
    UpdateView,
    DetailView,
    ListView,
)
from .models import Post
from django.urls import reverse_lazy
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    UserPassesTestMixin,
)


class PostListView(ListView):
    template_name = "posts/list.html"
    model = Post

class PostDetailView(DetailView):
    template_name = "posts/detail.html"
    model = Post

class PostCreateView(LoginRequiredMixin, CreateView):
    template_name = "posts/new.html"
    model = Post
    fields =["title", "subtitle", "body", "active"]

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    template_name = "posts/edit.html"
    model = Post
    fields =["title", "subtitle", "author", "active"]

def test_func(self):
    user = self.request.user
    post = self.get_object()
    return user == post.author

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    template_name = "posts/delete.html"
    model = Post
    success_url = reverse_lazy("list")

def test_func(self):
    user = self.request.user
    post = self.get_object()
    return user == post.author

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'home' %}">Blog</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link" href="{% url 'home' %}">Home</a>
                <a class="nav-link" href="{% url 'about' %}">About Us</a>
                {% if user.is_authenticated %}
                   <a class="nav-link" href="{% url 'list' %}">Posts</a>
                   <a class="nav-link" href="{% url 'new' %}">New Post</a>
                   <a class="nav-link" href="{% url 'password_change' %}">
                    Password Change</a>
                {% else %}
              <a class="nav-link" href="{% url 'login' %}">Log In</a>
                {% endif %}
            </div>
          </div>
        </div>
      </nav>
    <div class="container">
        {% block content %}{% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>

templates/pages/about.html
{% extends 'base.html' %}


{% block title %}About Us{% endblock title %}


{% block content %}
<h1>About Us</h1>
<p>Blogs R Us was founded in the fall of 2005 with a mission to keep users informed...</p>
{% endblock content %}

templates/pages/home.html
{% extends 'base.html' %}


{% block title %}Home{% endblock title %}


{% block content %}
<h1>Home</h1>
<p>Welcome to home page.</p>
{% endblock content %}

templates/pages/posts/list.html
{% extends 'base.html' %}


{% block title %}Posts{% endblock title %}


{% block content %}
<h1>Posts</h1>
<ul>
    {% for post in posts_list %}
    <li>{{ post.title }}</li>
    {% endfor %}
</ul>
{% endblock content %}

templates/pages/posts/new.html
{% extends 'base.html' %}


{% block title %}New Post{% endblock title %}


{% block content %}
<h1>New Post</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create" class="bt btn-success">
</form>
{% endblock content %}

templates/posts/delete.html
{% extends 'base.html' %}


{% block title %}Delete "{{ post.title }}"{% endblock title %}
 

{% block content %}
<h1>Delete Post</h1>
<p>Are you sure you want to delete "{{ post.title|truncatechars:100 }}"?</p>
<form methods="POST">
    {% csrf_token %}
    <input type="submit" value="Confirm" class="btn btn-danger">
</form>
{% endblock content %}

templates/posts/detail.html
{% extends 'base.html' %}


{% block title %}{{ post.title }}{% endblock title %}


{% block content %}
<h1>{{ post.title }}</h1>
<h3>{{ post.subtitle }}</h3>
<small>Created By: {{ post.author }} | On {{ post.created_on }}</small>
<p>{{ post.body }}</p>
{% endblock content %}

templates/posts/edit.html
{% extends 'base.html' %}


{% block title %}Edit "{{ post.title }}"{% endblock title %}


{% block content %}
<h1>Edit Post</h1>
<form methods="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Edit" class="btn btn-primary">
</form>
{% endblock content %}

templates/posts/list.html
{% extends 'base.html' %}


{% block title %}Posts{% endblock title %}


{% block content %}
<h1>Posts</h1>
<ul>
    {% for post in post_list %}
    <li>{{ post.title }}</li>
    {% endfor %}
</ul>
{% endblock content %}

templates/posts/new.html
{% extends 'base.html' %}


{% block title %}New Post{% endblock title %}


{% block content %}
<h1>New Post</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create" class="btn btn-success">
</form>
{% endblock content %}